name: RitualPulse
version: 1.0.1
main: fr.majestycraft.ritualpulse.RitualPulsePlugin
api-version: "1.20"
author: Capdrake
description: Retention rewards system (daily, streak, freeze, comeback, milestones)
softdepend: [PlaceholderAPI]

commands:
  ritual:
    description: Open RitualPulse GUI / claim reward / admin tools
    usage: /ritual [claim|reload|admin]
    aliases: [dailyritual, rpulse]

permissions:
  ritualpulse.use:
    description: Use RitualPulse
    default: true
  ritualpulse.admin:
    description: Admin commands for RitualPulse
    default: op
  ritualpulse.bypasscooldown:
    description: Bypass cooldown checks
    default: op
